---
title: Coding test results
output: html_document
params:
  test_data: list("x <- 2", "x <- 4")
framework: bootstrap
mode: selfcontained
widgets: "nyt_home"
highlighter: prettify
hitheme: twitter-bootstrap
assets:
  css:
    - "http://fonts.googleapis.com/css?family=Raleway:300"
    - "http://fonts.googleapis.com/css?family=Oxygen"
---

<style>
body{
  font-family: 'Oxygen', sans-serif;
  font-size: 16px;
  line-height: 24px;
}

h1,h2,h3,h4 {
  font-family: 'Raleway', sans-serif;
}

.container { width: 1000px; }
h3 {
  background-color: #D4DAEC;
  text-indent: 100px; 
}
h4 {
  text-indent: 100px;
}

g-table-intro h4 {
  text-indent: 0px;
}
</style>



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, results='asis', echo = FALSE}

library(magrittr)
library(glue)

hook <- knitr::hooks_html()$source
opts <- knitr::opts_chunk$get()

insert_user_comment <- function(comment, hook, opts){

  empty_comment <- !nchar(comment)
  if(empty_comment) return(NULL)

  cat("<b>The candidate provided the following comment: </b>")
  cat("\n\n")

  cat(hook(comment, options = opts))
  cat("\n\n")
  cat("\n\n")

}

insert_amt_hints <- function(amt_hints){

  hints <- ifelse(test = amt_hints == 1, yes = "hint", no = "hints")
  cat(glue("The candidate used {amt_hints} {hints}."))
  cat("\n\n")
  cat("\n\n")

}

insert_provided_code <- function(code_string, opts, is_r = TRUE){
  
  cat("<b>The code provided by the candidate reads: </b>")
  cat("\n\n")

  opts$highlight <- is_r
  cat(hook(code_string, options = opts))
  cat("\n\n")
  cat("\n\n")
  
}

insert_language <- function(language){
  
  cat(glue("{language} was used to answer this question."))
  cat("\n\n")
  
}


insert_question <- function(question){
  
  cat("  \n###", "Question", nr, ":  \n")
  cat(question)
  cat("\n\n")

}

insert_code_result <- function(code){

  cat("<b>The result provided by the candidate reads: </b>")
  cat("\n\n")
  
  is_plot <- grepl(pattern = "plot(", x = code, fixed = TRUE)
  if(is.data.frame(code)){
    
    print(knitr::kable(code))

  }else if(is_plot){
    
    eval(parse(text = code))
    
  }else{
    
    print(code)    
    
  }


  cat("\n\n")
  
}

insert_code_result_hint_language <- function(params){
  
  # code <- params$test_data$answers_result[[nr]] %>% gsub(pattern = "\n", replacement = "\n\n")
  code <- params$test_data$answers_result[[nr]]
  is_df <- is.data.frame(code)
  
  if(!is_df) code <- code %>% gsub(pattern = "\n", replacement = "\n\n")
   
  no_code <- !sum(nchar(code))
  if(no_code){
    
    cat("<b>The applicant did not provide code. </b>")
    cat("\n\n")
        
  }else{
    
    language <- params$test_data$used_language[[nr]]
    insert_language(language)

    insert_code_result(code)  
  
    code_string <- params$test_data$answers_code[[nr]]
    is_r <- params$test_data$used_language[[nr]] == "R"
    insert_provided_code(code_string, opts, is_r = is_r)
  
    amt_hints <- params$test_data$hint_nr[[nr]]
    insert_amt_hints(amt_hints)

  }
}

questions <- sapply(params$test_data$questions, "[", "text", USE.NAMES = FALSE) %>% as.character()

for(nr in seq(questions)){
   
  question <- questions[nr]
  insert_question(question)

  insert_code_result_hint_language(params)

  comment <- params$test_data$comments[[nr]]
  insert_user_comment(comment, hook, opts)

}

```
